version: '3'
services:
  go-app:
    container_name: gomyapp
    restart: on-failure:3
    build:
      dockerfile: Dockerfile.go
      context: . 
    depends_on:
      - db   
    ports:
      - "5001:8080"    
  db:
    image: mariadb    
    container_name: go-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=maria#go
      - MYSQL_DATABASE=golang
      - MYSQL_USER=gobase
      - MYSQL_PASSWORD=your1pass
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "5002:3306"
  pgadmin:
    container_name: go-admindb
    image: phpmyadmin
    restart: on-failure:3
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=18000M
    ports:
      - "5003:80"
